repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.12.17
    hooks:
      # Update the uv lockfile
      - id: uv-lock
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
      - id: codespell
        args: ["--write-changes"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.16.8"
    hooks:
      - id: ruff-format
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.399
    hooks:
      - id: pyright